
CREATE DATABASE notes;

USE notes;

CREATE TABLE user(
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(100) NOT NULL ,
last_name VARCHAR(100) NOT NULL ,
email VARCHAR(50) NOT NULL UNIQUE , 
password VARCHAR(70) NOT NULL
);

CREATE TABLE note (
id INT PRIMARY KEY AUTO_INCREMENT ,
user_id INT,
title VARCHAR(100) NOT NULL UNIQUE,
content VARCHAR(1500) NOT NULL ,
created_at DATETIME NOT NULL , 
updated_at DATETIME NOT NULL , 
FOREIGN KEY(user_id) REFERENCES user(id) 
);

CREATE TABLE document(
id INT PRIMARY KEY AUTO_INCREMENT , 
note_id INT ,
name VARCHAR(100) NOT NULL UNIQUE,
path VARCHAR(100) NOT NULL , 
type VARCHAR(10) NOT NULL ,
created_at DATETIME NOT NULL , 
updated_at DATETIME NOT NULL , 
FOREIGN KEY(note_id) REFERENCES note(id) 
);


